name: test-github-actions
on: [push]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Included Actions
      uses: actions/checkout@v2
    - name: Query User
      run: whoami
    - name: Query System
      run: uname -a
    - name: Test Print Variable
      env:
        TEST_VAR: "Test Var"
      run: |
        echo "Variable: ${TEST_VAR}"
    - name: Directory Info
      run: pwd && ls
    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: 1.10.7
        environment-file: .github/workflows/1.10.7.txt
    - name: Query Conda
      shell: bash -l {0}
      run: conda list
