name: test-github-actions
on: [push]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Included Actions
        - uses: actions/checkout@v2
          env:
            TEST_VAR="Test Var"
      - name: Query System
        run: whoami
        run: uname -a
        run: echo "${TEST_VAR}"
